### PR TITLE
Merging to developer track with OS image changes

### PR DESCRIPTION
**Pull request by balaji-suse**

### CODE REVIEW

**Comment by balaji-suse** [comment]
OS image changes

**Review by balaji-suse — COMMENTED** [review]
SUSE OS Image versions implementation

**Review by petersatsuse — CHANGES_REQUESTED** [review]
pls. review your changes, as you have created new variables, but do not use it right. At other places you removed variables and set fixed values - which is wrong too.
With this code it will not work as expected

**Comment by balaji-suse** [comment]
SUSE OS image version changes

**Review by petersatsuse — APPROVED** [review]
The changes need better commit descriptions and should be done in smaller chunks to be better trackable.

**Pull request merged**
