### PR TITLE
SUSE OS Images changes

### PR DESCRIPTION
**Pull request by balaji-suse**
SUSE OS Image selection implementation

### CODE REVIEW

**Comment by prasroy** [comment]
I am not getting a BYOS image for SLES 15 SP01 in the code. Could you please shed some light on it

**Comment by petersatsuse** [comment]
> I am not getting a BYOS image for SLES 15 SP01 in the code. Could you please shed some light on it

For 15SP1 the naming you need in the image section is a bit different, as it uses a different schema for SKU and offer.

Simply try to search the needed data with the az command.

I think for 15SP1 "offer": "sles-sap-15-sp1" and "sku": "gen1" or "gen2"
This comes from a issue of the marketplace with gen1/gen2 skus.

**Comment by prasroy** [comment]
> > I am not getting a BYOS image for SLES 15 SP01 in the code. Could you please shed some light on it
> 
> For 15SP1 the naming you need in the image section is a bit different, as it uses a different schema for SKU and offer.
> 
> Simply try to search the needed data with the az command.
> 
> I think for 15SP1 "offer": "sles-sap-15-sp1" and "sku": "gen1" or "gen2"
> This comes from a issue of the marketplace with gen1/gen2 skus.

Thanks a lot @petersatsuse for your answer. However I am specifically looking for BYOS packages with gen 1 as the virtual machine to be used in this case is gen 1. Gen 2 sku is mainly for teh Mv2 series which we released recently for higher memory (6 tb and 12 tb) config.
as you see below I am not getting any package when I am searching through 15-sp1.
prasenjit@Azure:~**$ az vm image show --location westeurope --urn SUSE:SLES-SAP-BYOS:15-sp1:latest
Artifact: VMImage was not found.**
prasenjit@Azure:~$ az vm image show --location westeurope --urn SUSE:SLES-SAP-BYOS:15:latest
{
  "automaticOsUpgradeProperties": {
    "automaticOsUpgradeSupported": false
  },
  "dataDiskImages": [],
  "hyperVgeneration": "V1",
  "id": "/Subscriptions/30c2b652-xxxxx-xxxx-8e2a-27xxxxxx01/Providers/Microsoft.Compute/Locations/westeurope/Publishers/SUSE/ArtifactTypes/VMImage/Offers/SLES-SAP-BYOS/Skus/15/Versions/2019.07.17",
  "location": "westeurope",
  "name": "2019.07.17",
  "osDiskImage": {
    "operatingSystem": "Linux",
    "sizeInBytes": 32212255232,
    "sizeInGb": 30
  },
  "plan": null,
  "tags": null
}

**Comment by petersatsuse** [comment]
az image show is the wrong command, as this show only your images you are using right now.

In general the path is
  Publisher > Offer > Sku > Image

Publisher: SUSE

Offers:
az vm image list-offers -l westus -p SUSE -o table

Location    Name
----------  ------
...
westus      SLES
westus      sles-15-sp1
westus      sles-15-sp1-basic
westus      sles-15-sp1-byos
westus      sles-15-sp1-hpc
westus      sles-15-sp1-hpc-byos
westus      SLES-BYOS
westus      SLES-Priority
westus      SLES-SAP
westus      sles-sap-15-sp1
westus      sles-sap-15-sp1-byos
westus      SLES-SAP-BYOS
...

Sku:
az vm image list-skus -l westus -f sles-sap-15-sp1-byos -p SUSE -o table

Location    Name
----------  ------
westus      gen1
westus      gen2


So now you have all data to fill in the ARM template the section for the image

minimal change
        "images": {
            "SLES for SAP 12 SP3 (Premium)": {
                "sku": "12-SP3",
                "offer": "SLES-SAP",
                "publisher": "SUSE",
                "version": "latest",
                "OSType": "Linux"
            }
        },
to
        "images": {
            "SLES for SAP 12 SP3 (Premium)": {
                "sku": "gen1",
                "offer": "sles-sap-15-sp1-byos",
                "publisher": "SUSE",
                "version": "latest",
                "OSType": "Linux"
            }
        },

but you should change the all the names too.
FYI we are preparing an update to use all actual valid images

**Comment by petersatsuse** [comment]
all changes got merge with another pull request

**Pull request closed without merging**
